### ISSUE TITLE
New use for Dragon Heads --> Dragon Breath Potions

### ISSUE THREAD

**Issue by theJavaWolf** [EarthMC/EMCRecipies#5]
In my personal opinion EMC is missing out a lot in terms of tipped arrows in combat.
There do exist some from past villager trading, but there aren't many anymore.

If there would be a way to obtian Dragonbreath you could use it to obtain 8 tipped arrows.
So here is my idea:
You could use 1 Dragon Head to obtain 3 Dragon Breath which would result in 24 arrows, thats not too much to flood the market but enough to make combat bit more interesting.

And Dragonheads have no use at all right now.

**Comment by jkmartindale** [comment]
As noted in EarthMC/Issue-Tracker#1348, dragon heads have no use at the moment because they're a cosmetic purchasable with real-world currency. I would love to get dragon breath in the game but it needs to be obtainable without using real-world currency or using in-game currency to buy something that ultimately came from real-world currency.

**Comment by theJavaWolf** [comment]
I am going to close this ticket so we can descuss in:
https://github.com/EarthMC/Issue-Tracker/issues/1348

Accidently made this ticket in the wrong spot so it is duplicate now.
